### ISSUE TITLE
Can't analyse udp server

### ISSUE THREAD

**Issue by QuentinGruber** [clinicjs/node-clinic-doctor#342]
Hi, I'm trying to use this tool to analyze a UDP server made with nodejs and the "Doctor has found data analysis issue". Is there a way to do this with clinic doctor or it's not supported ?

**Comment by mcollina** [comment]
It should be supported, maybe there is something else causing issues.. there is nothing related to UDP in doctor.

**Comment by QuentinGruber** [comment]
I've the issue with this project : https://github.com/H1emu/h1emu-server-dev/blob/main/ZoneServer.js , i've tried ` clinic doctor -- node ZoneServer.js`. The server run but when i shutdown it the clinic doctor display me an html page that display me "Doctor has found data analysis issue"

**Comment by mcollina** [comment]
Are you running any traffic throught it?

**Comment by QuentinGruber** [comment]
yep , i've also try something with autocannon but wasn't working too

**Comment by mcollina** [comment]
Can you please include/link a script to create load for that server? Autocannon does not support udp.

**Comment by QuentinGruber** [comment]
Running this script https://github.com/H1emu/h1emu-server-dev/blob/main/loginclient.js 
Create load for this server : https://github.com/H1emu/h1emu-server-dev/blob/main/loginserver.js
