### ISSUE TITLE
Version of @tensorflow/tfjs-core is outdated and depends on vulnerable node-fetch

### ISSUE THREAD

**Issue by marian-r** [clinicjs/node-clinic-doctor#365]
There is a [vulnerability in `node-fetch`](https://github.com/advisories/GHSA-w7rc-rwvf-8q5r) which has been patched and the latest `@tensorflow/tfjs-core` pulls the patched version, however the version of `@tensorflow/tfjs-core` used in this repo is outdated and therefore does not pull the patch. Would it be possible to upgrade `@tensorflow/tfjs-core`?

**Comment by mcollina** [comment]
Would you like to send a PR updating it? Thanks!

**Comment by marian-r** [comment]
@mcollina it seems it requires updates in [nearform/node-hidden-markov-model-tf](https://github.com/nearform/node-hidden-markov-model-tf) as well, but I couldn't make the tests work. Would you be able to help with upgrading TF in that repo at least?

**Comment by RafaelGSS** [comment]
@marian-r I have created a fix for you in the `hidden-markov-model` repo. When it releases you can start updating this repo :smile:

**Comment by RafaelGSS** [comment]
It's landed as v4 by the way.

**Comment by marian-r** [comment]
Done in #366

**Comment by marian-r** [comment]
#366 has landed in the main branch. Do you know when it could get released?

**Comment by RafaelGSS** [comment]
I think today.
