### ISSUE TITLE
--visualize-only utilizing 100% cpu for hours

### ISSUE THREAD

**Issue by JKKGBE** [clinicjs/node-clinic-doctor#370]
I did a 3 hour `clinic doctor --collect-only` run which resulted in 62 MB `processstat`, 4 kB `systeminfo` and 110 MB `traceevent` files. When I try to visualize the run in the first 30 seconds it creates a 191 MB `.html` file of which the last line is a full object ending with a comma, the `<script>` tag is unterminated. It then proceeds to utilize 100% cpu and doesn't finish for 8 hours at least. I only noticed the file not growing after that time, not sure if it matters.

```
clinic doctor: v9.2.1
nodejs: v10.23.0 (also tried v16.3.0 for visualization, but collection was done on v10.23.0)
```

**Comment by RafaelGSS** [comment]
Could you create a reproductible example?

**Comment by JKKGBE** [comment]
If you mean code then that's not possible. I could upload generated files if that helps?

**Comment by mcollina** [comment]
We should automatically exit after  the files have reached a certain size and document that.

The algorithms we use have an exponential big O if I recall correctly.

**Comment by JKKGBE** [comment]
Do you mean the collect files? Does that mean it could exit with incomplete files? Or it's possible that it's actually still doing something after that amount of time?

Please let me know if it helps if I upload the collect files and the html file.

Btw. by saying 100% cpu, I meant 100% of a single cpu thread.

**Comment by mcollina** [comment]
I mean that's never going to work, there is too much data for the current algorithms to process.

**Comment by JKKGBE** [comment]
Alright. Will I have any luck with Flame or Bubbleprof, or the same applies?

**Comment by mcollina** [comment]
I do not think anybody tested such big payloads. The only one that might support this is flame.

**Comment by JKKGBE** [comment]
We are trying to debug an error that occurs with time, hence the test length. I guess your software was designed for short tests and issues that can be replicated easily (or easier).

The visualization completed overnight, but the resulting html is borderline unusable due to lag.

Thank you for your assistance.
